import Foundation
import StorageService

// LikedPostEntity and its managed properties are generated by Xcode
// from LikedPosts.xcdatamodeld (Codegen: Class Definition).
extension LikedPostEntity {
    func makePost() -> Post {
        Post(
            author: author ?? "",
            description: postDescription ?? "",
            image: image ?? "",
            likes: Int(likes),
            views: Int(views)
        )
    }
}
